# setup-envs.ps1
# Automatically fetches Keycloak client secrets and writes .env.local files for all Darevel apps
# Run from repository root: .\scripts\setup-envs.ps1

Param()
$ErrorActionPreference = "Stop"

$BaseUrl = "http://localhost:8080"
$MasterRealm = "master"
$TargetRealm = "pilot180"
$AdminUser = "admin"
$AdminPass = "admin"

Write-Host "Requesting admin token..." -ForegroundColor Cyan
$body = @{
    grant_type = "password"
    client_id = "admin-cli"
    username = $AdminUser
    password = $AdminPass
}

try {
    $tokenResp = Invoke-WebRequest -Uri "$BaseUrl/realms/$MasterRealm/protocol/openid-connect/token" -Method POST -Body $body -ContentType "application/x-www-form-urlencoded"
    $tokenJson = $tokenResp.Content | ConvertFrom-Json
    $adminToken = $tokenJson.access_token

    if (-not $adminToken) {
        Write-Error "Failed to get admin token. Response: $($tokenResp.Content)"
        exit 1
    }
    Write-Host "Got admin token." -ForegroundColor Green
} catch {
    Write-Error "Failed to connect to Keycloak. Is it running on $BaseUrl? Error: $_"
    exit 1
}

$clientMap = @{
    "darevel-suite" = @{ app="suite"; port=3002 }
    "darevel-auth"  = @{ app="auth"; port=3005 }
    "darevel-chat"  = @{ app="chat"; port=3003 }
    "darevel-drive" = @{ app="drive"; port=3006 }
    "darevel-excel" = @{ app="excel"; port=3004 }
    "darevel-notify"= @{ app="notify"; port=3007 }
    "darevel-mail"  = @{ app="mail"; port=3008 }
    "darevel-slides"= @{ app="slides"; port=3000 }
}

foreach ($clientId in $clientMap.Keys) {
    $app = $clientMap[$clientId].app
    $port = $clientMap[$clientId].port
    Write-Host ""
    Write-Host "Processing client: $clientId -> apps/$app" -ForegroundColor Cyan

    try {
        $clientsResp = Invoke-WebRequest -Uri "$BaseUrl/admin/realms/$TargetRealm/clients?clientId=$clientId" -Headers @{ Authorization = "Bearer $adminToken" } -Method GET
        $clients = $clientsResp.Content | ConvertFrom-Json
        if ($clients.Length -eq 0) {
            Write-Warning "  Client $clientId not found in realm $TargetRealm. Skipping."
            continue
        }
        $internalId = $clients[0].id

        $secretResp = Invoke-WebRequest -Uri "$BaseUrl/admin/realms/$TargetRealm/clients/$internalId/client-secret" -Headers @{ Authorization = "Bearer $adminToken" } -Method GET
        $secretJson = $secretResp.Content | ConvertFrom-Json
        $secret = $secretJson.value

        if (-not $secret) {
            Write-Warning "  Secret not found for client $clientId. Maybe client is public. Writing empty secret placeholder."
            $secret = ""
        }
    } catch {
        Write-Warning "  Error fetching secret for $clientId : $_. Skipping."
        continue
    }

    $appPath = Join-Path -Path "apps" -ChildPath $app
    if (-not (Test-Path $appPath)) {
        New-Item -ItemType Directory -Path $appPath | Out-Null
    }

    $envFile = Join-Path $appPath ".env.local"
    if (Test-Path $envFile) {
        $timestamp = [int](Get-Date -UFormat %s)
        Copy-Item $envFile "$envFile.bak.$timestamp"
        Write-Host "  Backed up existing $envFile" -ForegroundColor Yellow
    }

    $appNameCapitalized = (Get-Culture).TextInfo.ToTitleCase($app)
    $envContent = @"
# === Darevel $appNameCapitalized App Environment ===
# Keycloak SSO Configuration - Auto-generated by setup-envs.ps1

# ===== Keycloak Config ($appNameCapitalized App - Port $port) =====
NEXT_PUBLIC_KEYCLOAK_URL=$BaseUrl
NEXT_PUBLIC_KEYCLOAK_REALM=$TargetRealm
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=$clientId
KEYCLOAK_CLIENT_SECRET=$secret
NEXT_PUBLIC_APP_URL=http://localhost:$port

# ===== Common Config =====
NEXTAUTH_COOKIE_DOMAIN=.darevel.local
NEXTAUTH_SECRET=darevel-nextauth-super-secret-2025
KEYCLOAK_ISSUER=$BaseUrl/realms/$TargetRealm

# ===== Redis & Database =====
REDIS_URL=redis://localhost:6379
DATABASE_URL=postgresql://postgres:postgres@localhost:5433/darevel

# ===== Service URLs =====
NEXTAUTH_URL=http://localhost:3005
SUITE_URL=http://localhost:3002
DRIVE_URL=http://localhost:3006
MAIL_URL=http://localhost:3008
SLIDES_URL=http://localhost:3000
CHAT_URL=http://localhost:3003
NOTIFY_URL=http://localhost:3007
EXCEL_URL=http://localhost:3004

# ===== API Gateway =====
API_GATEWAY_URL=http://localhost:8081

# ===== Development =====
NODE_ENV=development
TZ=Asia/Kolkata
"@

    $envContent | Out-File -FilePath $envFile -Encoding utf8 -NoNewline
    Write-Host "  Wrote $envFile" -ForegroundColor Green
}

Write-Host ""
Write-Host "✅ All done! Next steps:" -ForegroundColor Green
Write-Host "  1. Restart Keycloak: docker compose restart keycloak"
Write-Host "  2. Start your apps: npm run dev"
Write-Host ""
Write-Host "Test authentication with:" -ForegroundColor Cyan
Write-Host @"
Invoke-WebRequest -Uri "$BaseUrl/realms/$TargetRealm/protocol/openid-connect/token" ``
  -Method POST ``
  -Body @{
    grant_type = "password"
    client_id = "darevel-slides"
    client_secret = "<SECRET>"
    username = "demo@darevel.com"
    password = "demo123"
  } ``
  -ContentType "application/x-www-form-urlencoded" | Select-Object -ExpandProperty Content
"@
