#!/usr/bin/env bash
# setup-envs.sh
# Automatically fetches Keycloak client secrets and writes .env.local files for all Darevel apps
# Requires: curl, jq
set -euo pipefail

BASE_URL="http://localhost:8080"
MASTER_REALM="master"
TARGET_REALM="pilot180"
ADMIN_USER="admin"
ADMIN_PASS="admin"
APPS_DIRS=( "suite" "auth" "chat" "drive" "excel" "notify" "mail" "slides" )

echo "Requesting admin token..."
TOKEN_RESPONSE=$(curl -s -X POST "$BASE_URL/realms/$MASTER_REALM/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=password&client_id=admin-cli&username=$ADMIN_USER&password=$ADMIN_PASS")
ADMIN_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')

if [ -z "$ADMIN_TOKEN" ] || [ "$ADMIN_TOKEN" == "null" ]; then
  echo "Failed to get admin token. Response:"
  echo "$TOKEN_RESPONSE"
  exit 1
fi
echo "Got admin token."

# function to get client internal id by clientId
get_client_id() {
  local clientId="$1"
  curl -s -H "Authorization: Bearer $ADMIN_TOKEN" \
    "$BASE_URL/admin/realms/$TARGET_REALM/clients?clientId=$clientId" | jq -r '.[0].id'
}

# function to get secret by internal id
get_client_secret() {
  local internalId="$1"
  curl -s -H "Authorization: Bearer $ADMIN_TOKEN" \
    "$BASE_URL/admin/realms/$TARGET_REALM/clients/$internalId/client-secret" | jq -r '.value'
}

# mapping of client id -> app folder name & port
declare -A CLIENT_MAP=(
  [darevel-suite]="suite:3002"
  [darevel-auth]="auth:3005"
  [darevel-chat]="chat:3003"
  [darevel-drive]="drive:3006"
  [darevel-excel]="excel:3004"
  [darevel-notify]="notify:3007"
  [darevel-mail]="mail:3008"
  [darevel-slides]="slides:3000"
)

for client in "${!CLIENT_MAP[@]}"; do
  app_port="${CLIENT_MAP[$client]}"
  app="${app_port%%:*}"
  port="${app_port##*:}"
  echo ""
  echo "Processing client: $client -> apps/$app"
  CID=$(get_client_id "$client")
  if [ -z "$CID" ] || [ "$CID" == "null" ]; then
    echo "  ERROR: client '$client' not found in realm '$TARGET_REALM'. Skipping."
    continue
  fi
  SECRET=$(get_client_secret "$CID")
  if [ -z "$SECRET" ] || [ "$SECRET" == "null" ]; then
    echo "  WARNING: secret not found for client $client. Maybe client is public. Writing empty secret placeholder."
    SECRET=""
  fi

  APP_PATH="apps/$app"
  ENV_FILE="$APP_PATH/.env.local"

  mkdir -p "$APP_PATH"

  if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%s)"
    echo "  Backed up existing $ENV_FILE -> ${ENV_FILE}.bak"
  fi

  cat > "$ENV_FILE" <<EOF
# === Darevel ${app^} App Environment ===
# Keycloak SSO Configuration - Auto-generated by setup-envs.sh

# ===== Keycloak Config (${app^} App - Port $port) =====
NEXT_PUBLIC_KEYCLOAK_URL=$BASE_URL
NEXT_PUBLIC_KEYCLOAK_REALM=$TARGET_REALM
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=$client
KEYCLOAK_CLIENT_SECRET=$SECRET
NEXT_PUBLIC_APP_URL=http://localhost:$port

# ===== Common Config =====
NEXTAUTH_COOKIE_DOMAIN=.darevel.local
NEXTAUTH_SECRET=darevel-nextauth-super-secret-2025
KEYCLOAK_ISSUER=$BASE_URL/realms/$TARGET_REALM

# ===== Redis & Database =====
REDIS_URL=redis://localhost:6379
DATABASE_URL=postgresql://postgres:postgres@localhost:5433/darevel

# ===== Service URLs =====
NEXTAUTH_URL=http://localhost:3005
SUITE_URL=http://localhost:3002
DRIVE_URL=http://localhost:3006
MAIL_URL=http://localhost:3008
SLIDES_URL=http://localhost:3000
CHAT_URL=http://localhost:3003
NOTIFY_URL=http://localhost:3007
EXCEL_URL=http://localhost:3004

# ===== API Gateway =====
API_GATEWAY_URL=http://localhost:8081

# ===== Development =====
NODE_ENV=development
TZ=Asia/Kolkata
EOF

  echo "  Wrote $ENV_FILE"
done

echo ""
echo "✅ All done! Next steps:"
echo "  1. Restart Keycloak: docker compose restart keycloak"
echo "  2. Start your apps: npm run dev"
echo ""
echo "Test authentication with:"
echo "  curl -X POST \"$BASE_URL/realms/$TARGET_REALM/protocol/openid-connect/token\" \\"
echo "    -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "    -d \"grant_type=password\" \\"
echo "    -d \"client_id=darevel-slides\" \\"
echo "    -d \"client_secret=<SECRET>\" \\"
echo "    -d \"username=demo@darevel.com\" \\"
echo "    -d \"password=demo123\""
