import axios from 'axios';
import { GoogleGenerativeAI } from '@google/generative-ai';

/**
 * Email Service - Integrates with AI Email Assistant microservice
 *
 * This service acts as a proxy to your existing AI Email Assistant app.
 * It forwards email requests without handling SMTP directly.
 */

interface EmailConfig {
  emailAppUrl?: string;
  defaultRecipient?: string;
}

interface SendEmailParams {
  to: string | string[];
  subject: string;
  content: string;
  html?: string;
}

interface EmailResponse {
  success: boolean;
  message: string;
  data?: any;
}

/**
 * Get email configuration from environment
 */
function getEmailConfig(): EmailConfig {
  return {
    emailAppUrl: process.env.EMAIL_APP_URL,
    defaultRecipient: process.env.DEFAULT_EMAIL_RECIPIENT || process.env.ALERT_EMAIL
  };
}

/**
 * Send email via AI Email Assistant microservice
 */
export async function sendEmail(params: SendEmailParams): Promise<EmailResponse> {
  const config = getEmailConfig();

  if (!config.emailAppUrl) {
    console.warn('EMAIL_APP_URL not configured. Skipping email send.');
    return {
      success: false,
      message: 'Email service not configured'
    };
  }

  try {
    // Ensure recipients is an array
    const recipients = Array.isArray(params.to) ? params.to : [params.to];

    // Forward request to AI Email Assistant microservice
    const response = await axios.post(config.emailAppUrl, {
      recipients,
      subject: params.subject,
      html: params.html || params.content,
      text: params.content
    }, {
      timeout: 15000,
      headers: {
        'Content-Type': 'application/json'
      }
    });

    console.log(`✅ Email sent successfully: "${params.subject}" to ${recipients.join(', ')}`);

    return {
      success: true,
      message: 'Email sent successfully',
      data: response.data
    };
  } catch (error: any) {
    console.error('Email send error:', error.message);

    return {
      success: false,
      message: 'Failed to send email',
      data: {
        error: error.message,
        details: error.response?.data
      }
    };
  }
}

/**
 * Send meeting summary via email
 */
export async function sendMeetingSummary(
  summary: string,
  title: string,
  recipients?: string[]
): Promise<EmailResponse> {
  const config = getEmailConfig();
  const to = recipients || (config.defaultRecipient ? [config.defaultRecipient] : []);

  if (to.length === 0) {
    return {
      success: false,
      message: 'No recipients specified and no default recipient configured'
    };
  }

  const subject = `Meeting Summary: ${title}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0;">
        <h1 style="margin: 0; font-size: 28px;">📝 Meeting Summary</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">${title}</p>
      </div>

      <div style="background-color: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px;">
        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
          <h2 style="color: #4f46e5; margin-top: 0;">Summary Content</h2>
          <div style="white-space: pre-wrap; line-height: 1.6; color: #374151;">
${summary}
          </div>
        </div>

        <div style="margin-top: 30px; padding: 20px; background: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 4px;">
          <p style="margin: 0; color: #1e40af; font-size: 14px;">
            <strong>💡 Tip:</strong> This summary was automatically generated by Darevel Chat AI Chat App.
            Review the full conversation in your dashboard for more details.
          </p>
        </div>

        <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          <p style="margin: 0;">
            Generated by <strong>Darevel Chat</strong><br>
            ${new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  `;

  return sendEmail({
    to,
    subject,
    content: summary,
    html
  });
}

/**
 * Send incident report via email
 */
export async function sendIncidentReport(
  incidentData: {
    podName: string;
    namespace: string;
    severity: string;
    rootCause: string;
    remediationSteps: string[];
    timestamp: Date;
  },
  recipients?: string[]
): Promise<EmailResponse> {
  const config = getEmailConfig();
  const to = recipients || (config.defaultRecipient ? [config.defaultRecipient] : []);

  if (to.length === 0) {
    return {
      success: false,
      message: 'No recipients specified and no default recipient configured'
    };
  }

  const severityColors: Record<string, string> = {
    critical: '#dc2626',
    high: '#ea580c',
    medium: '#ca8a04',
    low: '#2563eb'
  };

  const severityColor = severityColors[incidentData.severity] || '#6b7280';

  const subject = `🚨 Incident Report: ${incidentData.podName} (${incidentData.severity.toUpperCase()})`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
      <div style="background-color: ${severityColor}; color: white; padding: 30px; border-radius: 10px 10px 0 0;">
        <h1 style="margin: 0; font-size: 28px;">🚨 Kubernetes Incident Report</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">${incidentData.podName}</p>
      </div>

      <div style="background-color: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px;">
        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px;">
          <h2 style="color: #4f46e5; margin-top: 0;">Incident Details</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #374151; width: 150px;">Pod Name:</td>
              <td style="padding: 10px 0; color: #6b7280;">${incidentData.podName}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #374151;">Namespace:</td>
              <td style="padding: 10px 0; color: #6b7280;">${incidentData.namespace}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #374151;">Severity:</td>
              <td style="padding: 10px 0;">
                <span style="background-color: ${severityColor}; color: white; padding: 4px 12px; border-radius: 4px; font-weight: bold; text-transform: uppercase;">
                  ${incidentData.severity}
                </span>
              </td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #374151;">Timestamp:</td>
              <td style="padding: 10px 0; color: #6b7280;">${incidentData.timestamp.toLocaleString()}</td>
            </tr>
          </table>
        </div>

        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px;">
          <h2 style="color: #dc2626; margin-top: 0;">🔍 Root Cause Analysis</h2>
          <div style="background-color: #fef2f2; border-left: 4px solid #dc2626; padding: 15px; border-radius: 4px;">
            <p style="margin: 0; color: #374151; line-height: 1.6;">
              ${incidentData.rootCause}
            </p>
          </div>
        </div>

        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
          <h2 style="color: #2563eb; margin-top: 0;">🔧 Remediation Steps</h2>
          <ol style="margin: 0; padding-left: 20px; color: #374151; line-height: 1.8;">
            ${incidentData.remediationSteps.map(step => `<li style="margin-bottom: 8px;">${step}</li>`).join('')}
          </ol>
        </div>

        <div style="margin-top: 30px; padding: 20px; background: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 4px;">
          <p style="margin: 0; color: #1e40af; font-size: 14px;">
            <strong>💡 Action Required:</strong> Review the incident in your Darevel Chat dashboard for complete details and mark as resolved once addressed.
          </p>
        </div>

        <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          <p style="margin: 0;">
            Generated by <strong>Darevel Chat Incident Management</strong><br>
            ${new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  `;

  const content = `
Incident Report: ${incidentData.podName}

Pod Name: ${incidentData.podName}
Namespace: ${incidentData.namespace}
Severity: ${incidentData.severity.toUpperCase()}
Timestamp: ${incidentData.timestamp.toLocaleString()}

Root Cause Analysis:
${incidentData.rootCause}

Remediation Steps:
${incidentData.remediationSteps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---
Generated by Darevel Chat Incident Management
${new Date().toLocaleString()}
  `.trim();

  return sendEmail({
    to,
    subject,
    content,
    html
  });
}

/**
 * Send pod analytics report via email
 */
export async function sendAnalyticsReport(
  stats: {
    totalIncidents: number;
    mttr: number;
    topFailingPods: { podName: string; count: number }[];
    severityBreakdown: Record<string, number>;
  },
  recipients?: string[]
): Promise<EmailResponse> {
  const config = getEmailConfig();
  const to = recipients || (config.defaultRecipient ? [config.defaultRecipient] : []);

  if (to.length === 0) {
    return {
      success: false,
      message: 'No recipients specified and no default recipient configured'
    };
  }

  const subject = `📊 Kubernetes Analytics Report - ${new Date().toLocaleDateString()}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0;">
        <h1 style="margin: 0; font-size: 28px;">📊 Analytics Report</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">${new Date().toLocaleDateString()}</p>
      </div>

      <div style="background-color: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px;">
        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px;">
          <h2 style="color: #4f46e5; margin-top: 0;">Overview</h2>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
            <div style="text-align: center; padding: 20px; background: #f3f4f6; border-radius: 8px;">
              <div style="font-size: 36px; font-weight: bold; color: #4f46e5;">${stats.totalIncidents}</div>
              <div style="color: #6b7280; margin-top: 5px;">Total Incidents</div>
            </div>
            <div style="text-align: center; padding: 20px; background: #f3f4f6; border-radius: 8px;">
              <div style="font-size: 36px; font-weight: bold; color: #059669;">${Math.round(stats.mttr / 60)}m</div>
              <div style="color: #6b7280; margin-top: 5px;">Avg MTTR</div>
            </div>
          </div>
        </div>

        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px;">
          <h2 style="color: #4f46e5; margin-top: 0;">Severity Breakdown</h2>
          ${Object.entries(stats.severityBreakdown).map(([severity, count]) => `
            <div style="margin-bottom: 10px;">
              <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                <span style="text-transform: capitalize; color: #374151;">${severity}</span>
                <span style="font-weight: bold; color: #6b7280;">${count}</span>
              </div>
              <div style="background: #e5e7eb; height: 8px; border-radius: 4px; overflow: hidden;">
                <div style="background: ${severity === 'critical' ? '#dc2626' : severity === 'high' ? '#ea580c' : severity === 'medium' ? '#ca8a04' : '#2563eb'}; height: 100%; width: ${(count / stats.totalIncidents * 100)}%;"></div>
              </div>
            </div>
          `).join('')}
        </div>

        <div style="background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
          <h2 style="color: #4f46e5; margin-top: 0;">Top Failing Pods</h2>
          <ol style="margin: 0; padding-left: 20px; color: #374151; line-height: 2;">
            ${stats.topFailingPods.slice(0, 5).map(pod => `
              <li><strong>${pod.podName}</strong> - ${pod.count} incidents</li>
            `).join('')}
          </ol>
        </div>

        <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          <p style="margin: 0;">
            Generated by <strong>Darevel Chat Analytics</strong><br>
            ${new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  `;

  return sendEmail({
    to,
    subject,
    content: `Analytics Report for ${new Date().toLocaleDateString()}`,
    html
  });
}

/**
 * Generate AI-powered subject line suggestions
 */
export async function suggestSubjectLines(
  content: string,
  type?: 'summary' | 'incident' | 'analytics' | 'generic'
): Promise<EmailResponse & { suggestions?: string[] }> {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      console.warn('GEMINI_API_KEY not configured. Returning default suggestions.');

      // Return contextual default suggestions based on type
      const defaultSuggestions = getDefaultSuggestions(type);

      return {
        success: true,
        message: 'Using default subject suggestions (Gemini API not configured)',
        suggestions: defaultSuggestions
      };
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    const contextPrompt = getContextPromptForType(type);

    const prompt = `
${contextPrompt}

Generate 3 professional and engaging email subject lines for the following email content.
The subject lines should be:
- Concise (under 60 characters)
- Action-oriented or informative
- Professional yet engaging
- Different in tone/style from each other

Email content:
${content.slice(0, 500)}

Return ONLY the 3 subject lines, one per line, without numbering or bullet points.`;

    const result = await model.generateContent(prompt);
    const response = result.response.text();

    // Parse response into array of suggestions
    const suggestions = response
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0 && !line.match(/^[\d\.\-\*]/)) // Remove numbering/bullets
      .slice(0, 3); // Ensure max 3 suggestions

    // If AI didn't return enough suggestions, supplement with defaults
    if (suggestions.length < 3) {
      const defaults = getDefaultSuggestions(type);
      while (suggestions.length < 3) {
        const nextDefault = defaults[suggestions.length];
        if (nextDefault && !suggestions.includes(nextDefault)) {
          suggestions.push(nextDefault);
        } else {
          break;
        }
      }
    }

    return {
      success: true,
      message: 'Subject suggestions generated successfully',
      suggestions
    };
  } catch (error: any) {
    console.error('Subject suggestion error:', error.message);

    // Fallback to default suggestions on error
    const defaultSuggestions = getDefaultSuggestions(type);

    return {
      success: true,
      message: 'Using default suggestions due to error',
      suggestions: defaultSuggestions
    };
  }
}

/**
 * Get context-specific prompt based on email type
 */
function getContextPromptForType(type?: string): string {
  switch (type) {
    case 'summary':
      return 'You are generating subject lines for a meeting summary email.';
    case 'incident':
      return 'You are generating subject lines for a Kubernetes incident report email. Include severity or urgency indicators.';
    case 'analytics':
      return 'You are generating subject lines for a Kubernetes analytics report email with metrics and statistics.';
    default:
      return 'You are generating subject lines for a professional business email.';
  }
}

/**
 * Get default subject line suggestions based on email type
 */
function getDefaultSuggestions(type?: string): string[] {
  switch (type) {
    case 'summary':
      return [
        'Meeting Summary: Key Outcomes & Action Items',
        'Quick Recap: Today\'s Meeting Highlights',
        'Action Items & Insights from Team Sync'
      ];
    case 'incident':
      return [
        '🚨 Incident Alert: Immediate Attention Required',
        'Critical Pod Failure: Action Needed',
        'Incident Report: Resolution Steps Included'
      ];
    case 'analytics':
      return [
        '📊 Kubernetes Analytics Report - Weekly Overview',
        'Performance Insights: Your K8s Cluster Summary',
        'Analytics Digest: Incidents & MTTR Breakdown'
      ];
    default:
      return [
        'Important Update: Please Review',
        'Action Required: Time-Sensitive Information',
        'Summary Report: Key Information Enclosed'
      ];
  }
}
